version: '3'

services:
  #reverse proxy
  reverse-proxy:
    build: reverse-proxy/
    restart: always
    ports:
     - 8080:80
    links:
    - wordpress
    - phpmyadmin
    - sitea
    - siteb
    - sitec
  #wordpress
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_NAME: site_wordpress
    networks:
      - default
      - wpdbnet
  #wordpress db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: site_wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd
    networks:
      - default
      - wpdbnet
  #wordpress phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db:db
    networks:
      - default
      - wpdbnet
  #site A
  sitea:
    build: siteA/     
  #site B
  siteb:
    build: siteB/

  #load balancer
  sitec:
    build: siteC/LoadBalancer/
    links:
      - sitec1
      - sitec2 
  #site C 1 and 2 for load balancer demo
  sitec1:
    build: siteC/site1/
  sitec2:
    build: siteC/site2/

networks:
  wpdbnet:
