version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8084:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_NAME: site_wordpress

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: site_wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db:db
    ports:
      - 8083:80
