version: '3'

services:
  #reverse proxy
  reverse-proxy:
    #build: .
    image: nginx
    restart: always
    ports:
     - 8080:80
    links:
    - wordpress
    - phpmyadmin
    environment:
     - NGINX_HOST=local.training.ovh
     - NGINX_PORT=80

  #wordpress
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_NAME: site_wordpress
    networks:
      - wpdbnet
  #wordpress db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: site_wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd
    networks:
      - wpdbnet
  #wordpress phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db:db
    ports:
      - 8083:80
    networks:
      - wpdbnet

networks:
  wpdbnet:
