version: '3'

services:
  reverse-proxy:
    image: nginx
    restart: always
    ports:
     - 8080:80
    environment:
     - NGINX_HOST=local.training.ovh
     - NGINX_PORT=80
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
